site_name: Yilin Fang
site_url: https://yilinfang.top
site_description: Personal website of Yilin Fang
site_author: Yilin Fang
copyright: Copyright &copy; 2025 Yilin Fang. All rights reserved.
theme:
  name: material
  icon:
    logo: material/home
  favicon: null
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
